substitutions:
  name: victron-mppt-esp32
  external_components_source: github://KinDR007/VictronMPPT-ESPHOME@main


esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino
external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
   static_ip: 192.168.178.102
   gateway: 192.168.178.1
   subnet: 255.255.255.0

web_server:
  port: 80


ota:

logger:



mqtt:
  broker: !secret mqtt_host
  port: 1884
  username: Maurice
  password: !secret mqtt_password

uart:
  id: uart_0
  tx_pin: GPIO16  # Not connected! The communication is read-only
  rx_pin: GPIO17  # Connect this this GPIO and GND to the MPPT charger
  baud_rate: 19200
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    max_power_yesterday:
      name: "${name} max power yesterday"
    max_power_today:
      name: "${name} max power today"
    yield_total:
      name: "${name} yield total"
    yield_yesterday:
      name: "${name} yield yesterday"
    yield_today:
      name: "${name} yield today"
    panel_voltage:
      name: "${name} panel voltage"
    panel_power:
      name: "${name} panel power"
    battery_current:
      name: "${name} panel current"
    battery_voltage:
      name: "${name} battery voltage"
    day_number:
      name: "${name} day number"
    charging_mode_id:
      name: "${name} charging mode id"
    error_code:
      name: "${name} error code"
    tracking_mode_id:
      name: "${name} tracking mode id"
    load_current:
      name: "${name} load current"

    

text_sensor:
  - platform: victron
    victron_id: victron0
    model_description:
      name: "${name} model description"
    charging_mode:
      name: "${name} charging mode"
    error:
      name: "${name} error"
    tracking_mode:
      name: "${name} tracking mode"
    firmware_version:
      name: "${name} firmware version"
    device_type:
      name: "${name} device type"
    serial_number:
      name: "${name} serial number"

binary_sensor:
  - platform: victron
    victron_id: victron0
    load_state:
      name: "${name} load state"
    relay_state:
      name: "${name} relay state"
