substitutions:
  name: victron-mppt-esp32
  external_components_source: github://KinDR007/VictronMPPT-ESPHOME@main


esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino
external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
   static_ip: 192.168.178.102
   gateway: 192.168.178.1
   subnet: 255.255.255.0

web_server:
  port: 80


ota:

logger:



mqtt:
  broker: !secret mqtt_host
  port: 1884
  username: Maurice
  password: !secret mqtt_password

uart:
  id: uart_0
  tx_pin: GPIO16  # Not connected! The communication is read-only
  rx_pin: GPIO17  # Connect this this GPIO and GND to the MPPT charger
  baud_rate: 19200
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    max_power_yesterday:
      name: "Max Power Yesterday"
    max_power_today:
      name: "Max Power Today"
    yield_total:
      name: "Total Yield"
    yield_yesterday:
      name: "Yield Yesterday"
    yield_today:
      name: "Yield Today"
    panel_voltage:
      name: "Panel Voltage"
    panel_power:
      name: "Panel Power"
    battery_voltage:
      name: "Battery Voltage"
    battery_voltage_2:
      name: "Battery Voltage 2"
    battery_voltage_3:
      name: "Battery Voltage 3"
    battery_current:
      name: "Battery Current"
    battery_current_2:
      name: "Battery Current 2"
    battery_current_3:
      name: "Battery Current 3"
    day_number:
      name: "Day Number"
    charging_mode_id:
      name: "Charging Mode ID"
    error_code:
      name: "Error Code"
    tracking_mode_id:
      name: "Tracking Mode ID"
    load_current:
      name: "Load Current"
    ac_out_voltage:
      name: "AC Output Voltage"
    ac_out_current:
      name: "AC Output Current"
    ac_out_apparent_power:
      name: "AC Output Apparent Power"
    device_mode_id:
      name: "Device Mode ID"
    warning_code:
      name: "Warning Code"
    battery_temperature:
      name: "Battery Temperature"
    instantaneous_power:
      name: "Instantaneous Power"
    consumed_amp_hours:
      name: "Consumed Amp Hours"
    state_of_charge:
      name: "State of Charge"
    time_to_go:
      name: "Time to Go"
    depth_of_the_deepest_discharge:
      name: "Depth of the Deepest Discharge"
    depth_of_the_last_discharge:
      name: "Depth of the Last Discharge"
    depth_of_the_average_discharge:
      name: "Depth of the Average Discharge"
    number_of_charge_cycles:
      name: "Number of Charge Cycles"
    number_of_full_discharges:
      name: "Number of Full Discharges"
    cumulative_amp_hours_drawn:
      name: "Cumulative Amp Hours Drawn"
    min_battery_voltage:
      name: "Minimum Battery Voltage"
    max_battery_voltage:
      name: "Maximum Battery Voltage"
    last_full_charge:
      name: "Last Full Charge"
    number_of_automatic_synchronizations:
      name: "Number of Automatic Synchronizations"
    number_of_low_main_voltage_alarms:
      name: "Number of Low Main Voltage Alarms"
    number_of_high_main_voltage_alarms:
      name: "Number of High Main Voltage Alarms"
    number_of_low_auxiliary_voltage_alarms:
      name: "Number of Low Auxiliary Voltage Alarms"
    number_of_high_auxiliary_voltage_alarms:
      name: "Number of High Auxiliary Voltage Alarms"
    min_auxiliary_battery_voltage:
      name: "Minimum Auxiliary Battery Voltage"
    max_auxiliary_battery_voltage:
      name: "Maximum Auxiliary Battery Voltage"
    amount_of_discharged_energy:
      name: "Amount of Discharged Energy"
    amount_of_charged_energy:
      name: "Amount of Charged Energy"

    

text_sensor:
  - platform: victron
    victron_id: victron0
    model_description:
      name: "${name} model description"
    charging_mode:
      name: "${name} charging mode"
    error:
      name: "${name} error"
    tracking_mode:
      name: "${name} tracking mode"
    firmware_version:
      name: "${name} firmware version"
    device_type:
      name: "${name} device type"
    serial_number:
      name: "${name} serial number"

binary_sensor:
  - platform: victron
    victron_id: victron0
    load_state:
      name: "${name} load state"
    relay_state:
      name: "${name} relay state"
